---
# tasks file for cms

- name: Create local_settings.py
  template: src="../../../../django/mainapp/local_settings.py.j2"
    dest="{{ ansible_env.HOME }}/{{ app_dir }}/django/mainapp/local_settings.py"

- name: Migrate django database
  shell: "{{ ansible_env.HOME }}/.virtualenvs/{{ cms_virtualenv }}/bin/python {{ ansible_env.HOME }}/{{ app_dir }}/django/manage.py migrate" 

- name: Collect django static files
  shell: "{{ ansible_env.HOME }}/.virtualenvs/{{ cms_virtualenv }}/bin/python {{ ansible_env.HOME }}/{{ app_dir }}/django/manage.py collectstatic --noinput"

- name: Create pythonanywhere wsgi
  template: src="../../../../django/wsgi.py.j2"
    dest="/var/www/{{ wsgi_name }}.py"
