#!/bin/bash  
f=$1

[[ $0 != "$BASH_SOURCE" ]] && exittype="return" || exittype="exit 1"

if [ "$1" == "-s" ] || [ "$1" == "-d" ]; then
	if [ $0 == "$BASH_SOURCE" ]; then
		echo "Script must be sourced with '. $0'"
		$exittype
	fi 
fi

if [ "$1" == "-d" ]; then
	rm ~/.vaultpw
	echo Deleted ~/.vaultpw
	echo Unset ANSIBLE_VAULT_PASSWORD_FILE
	export ANSIBLE_VAULT_PASSWORD_FILE=
	$exittype
fi

tmpf="$1.decrypted"
tmpfe="`mktemp /tmp/onchange.XXXXX`"

echo -n "Enter vault password and press [ENTER]: "
read vaultpw

if [ "$1" == "-s" ]; then
	echo $vaultpw > ~/.vaultpw
	echo Saved ~/.vaultpw
	echo Set ANSIBLE_VAULT_PASSWORD_FILE=~/.vaultpw
	echo "Remember to run '. vaultedit -d' when done"
	export ANSIBLE_VAULT_PASSWORD_FILE=~/.vaultpw
	$exittype
fi

if [ "$vaultpw" == "" ]; then
	if [ ! -f ~/.vaultpw ]; then
  	    echo ~/.vaultpw not found, run '. vaultedit -s'
	fi
	cp ~/.vaultpw ~/.vaultpw.ed
else
	echo $vaultpw > ~/.vaultpw.ed
fi

trap "rm $tmpf; rm $tmpfe; rm ~/.vaultpw.ed; $exittype" 2

SUBLIME="`cygpath 'C:\Program Files\Sublime Text 3\subl.exe'`"
#SUBLIME=echo

cp "$f" "$tmpf"

ansible-vault decrypt "$tmpf" --vault-password-file ~/.vaultpw.ed

cp "$tmpf" "$tmpfe"  

if [ "$2" != "-n" ]; then
  "$SUBLIME" "`cygpath -w $tmpf`"
fi

while : ; do  
    if [ "$tmpf" -nt "$tmpfe" ]; then  
        cp "$tmpf" "$tmpfe"  
        cp "$tmpf" "$f"
        ansible-vault encrypt "$f" --vault-password-file ~/.vaultpw.ed        
    fi  
    sleep 2  
done  