
- name: install nginx
  hosts: local
  become: true
  become_user: root
  pre_tasks:
  - name: why sudo time out?
    lineinfile: dest=/etc/hosts line="127.0.0.1 {{ inventory_hostname }}"
  roles:
    - geerlingguy.nodejs
    - jdauphant.nginx
    - ANXS.postgresql
    - uwsgi
    - express

