- name: configure and deploy the app
  hosts: paw
  remote_user: fivethreeo
  roles:
    - cms

- name: collect facts
  hosts: local
  tasks:
    - name: collect facts
      setup:
  tags:
    - facts

