
- name: install nginx
  hosts: local
  become: true
  become_user: root
  pre_tasks:
  - name: why sudo time out?
    lineinfile: dest=/etc/hosts line="127.0.0.1 {{ inventory_hostname }}"
  - name: add user
    user:
      name: appuser
      group: www-data
  - name: install the latest version of libpq-dev
    package:
      name: libpq-dev 
      state: latest
  - name: make sure checkouts are present
    git:
      accept_hostkey: "{{ item.accept_hostkey|default(omit) }}"
      bare: "{{ item.bare|default(omit) }}"
      clone: "{{ item.clone|default(omit) }}"
      depth: "{{ item.depth|default(omit) }}"
      dest: "{{ item.dest|default(omit) }}"
      executable: "{{ item.executable|default(omit) }}"
      force: "{{ item.force|default(omit) }}"
      key_file: "{{ item.key_file|default(omit) }}"
      recursive: "{{ item.recursive|default(omit) }}"
      reference: "{{ item.reference|default(omit) }}"
      refspec: "{{ item.refspec|default(omit) }}"
      remote: "{{ item.remote|default(omit) }}"
      repo: "{{ item.repo|default(omit) }}"
      ssh_opts: "{{ item.ssh_opts|default(omit) }}"
      track_submodules: "{{ item.track_submodules|default(omit) }}"
      umask: "{{ item.umask|default(omit) }}"
      update: "{{ item.update_revisions|default(omit) }}"
      verify_commit: "{{ item.verify_commit|default(omit) }}"
      version: "{{ item.version|default(omit) }}"
    when: "{{ item.present|default(False) }}"
    with_items: "{{ checkouts }}"
  - name: make sure checkouts have the correct permissions
    file:
      path: "{{ item.dest|default(omit) }}"
      state: directory
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      recurse: yes
    when: "{{ item.present|default(False) }}"
    with_items: "{{ checkouts }}"
  - name: make sure checkouts are absent
    file:
      dest: "{{ item.dest|default(omit) }}"
      state: absent
    when: "{{ item.absent|default(False) }}"
    with_items: "{{ checkouts }}"
  roles:
  #   - virtualenv
  #   - geerlingguy.nodejs
  #   - ANXS.postgresql
  #   - geerlingguy.memcached
  #   - django
  #   - uwsgi
  #   - express
  #   - jdauphant.nginx
  #   - ansible-elasticsearch
    - SimpliField.rabbitmq

